#!/bin/bash

HOSTNAME=${1:-devbox}

if [ -z "$(type docker-machine 2> /dev/null)" ]; then
	OPTs="-v /home/dev/save/$HOSTNAME:/home/dev/save:rw"
else
	OPTs="-v $HOME/devboxes/$HOSTNAME:/home/dev/save:rw"
	mkdir -p $HOME/devboxes/$HOSTNAME
fi

NETWORK=$(docker network create $HOSTNAME 2> /dev/null)
docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm $OPTs --net=$HOSTNAME -h $HOSTNAME fernandocorrea/devbox
if [ x$NETWORK != x ]; then
	docker network rm $HOSTNAME
fi
