#!/bin/bash

HOSTNAME=${1:-devbox}

if [ -z "$(type docker-machine 2> /dev/null)" ]; then
	OPTs="-v /home/dev/save/$HOSTNAME:/home/dev/save:rw"
else
	OPTs="-v $HOME/devboxes/$HOSTNAME:/home/dev/save:rw"
	mkdir -p $HOME/devboxes/$HOSTNAME
fi

#echo docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm $OPTs -h $HOSTNAME devbox
docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm $OPTs -h $HOSTNAME devbox
