#!/bin/bash
FILENAME=${1:-Test}
FILE=$FILENAME.java

[ -f $FILE ] || cat <<END >$FILE
public class $FILENAME { 
	public static void main(String[] args) {
		System.out.println("$FILENAME");
	}
}
END

vim $FILE
javac $FILE && java $FILENAME

